### ISSUE TITLE
Consistent ASB_GIT_REPO url when using https or ssh

### ISSUE THREAD

**Issue by AAkindele** [retaildevcrews/aks-secure-baseline-hack-template#364]
The instructions for setting the `ASB_GIT_REPO` variable for flux only works when the remote url is https. The flux deployment is not setup to work with the ssh url.

Update the command to generate the https url in both cases.

Example:

```bash
# origin url when cloning with https
https://github.com/retaildevcrews/asb-hack.git

# origin url when cloning with ssh
git@github.com:retaildevcrews/asb-hack.git

# in either scenario, update README instructions so 'ASB_GIT_REPO' is set to 'https://github.com/retaildevcrews/asb-hack.git'
```

**Comment by bartr** [comment]
- you might be able to get some ideas from the oh-my-zsh code

**Comment by alfredoihernandez** [comment]
> * you might be able to get some ideas from the oh-my-zsh code

I tried looking for ideas there and using insteadOf from git but ended up using RegEx substitution
