### ISSUE TITLE
General Notes on SPARK feedback

### ISSUE THREAD

**Issue by AAkindele** [retaildevcrews/aks-secure-baseline-hack-template#366]
~strike through~ has been addressed in a PR
:green_book: Process Improvement
:blue_book: Actionable Issues
:orange_book: DevExp Feedback
:bulb: Challenge Ideas

- ~give more info in advance before hack starts~
  - ~A "Pre-session" is what we do when we do it with customers on these two-day workshops. It's an office hour about three days before the workshop.~
- ~Send out calendar reminders earlier. I had people in my group that didn't get a calendar invite and thought they weren't accepted.~
- ~Send out team assignments earlier to the members of a team. Also, if possible send the teams meeting for the individual teams before the actual event (this will also help with tracking who will/will not attend)~
- :green_book: Maybe consider an EMEA friendly timezone. I had 2 people from EMEA in the group, and they worked till 10PM.
- :green_book: 2 days for the hackathon in SPARK is a big commitment. Might have to miss other sessions live and miss on the interactions.
- :blue_book: For challenge 1, add some hints on how to generate failure traffic to show up in the logs
  - add some sample queries for the different type of logs
  - https://github.com/wallarm/gotestwaf
- :blue_book: Be more clear about challenges that are related to each other
- :blue_book: How to generate failure traffic... oppty for webv? i.e. how can one challenge contribute to another
  - Running webv first could perhaps generate a bunch of traffic, including (deliberately?) failed traffic for the monitoring challenge
  - And then something like webv could target both 80 and 443 to generate fail signals, then challenge 2 could be about see those fails, now what can we do about that? Hey how about a redirect?
- ~Main README: remove link to RDC~
- :blue_book: Challenge 1: A screenshot showing target dashboard would be great hint
- :blue_book: Challenge 2: Add hint about allowing port 80 in part 1. ~301 status should be expected instead of 302~
- :blue_book: Challenge 3: Overall confusion about the ACR strategy
- :blue_book: Maybe another challenge on flux?
- :bulb: would love to have more challenges on the integrations that we are pitching to our customers as a competitive advantage, such as Azure Policy integration and AAD Pod Identity
- :orange_book: "First time user, it worked great!"
  - re: codespaces
- :orange_book: "A huge thank you to the organizers and coaches. The coaches were amazing, supportive and so very helpful in learning!"
- :orange_book: "I don't think I'm going back to desktop vscode -- if i can avoid it lol"
  - re: codespaces
- :orange_book: "Same here.  First time. Enjoyed seeing it in action"
  - re: codespaces
- :orange_book: "First time user as well, it worked great for me too"
  - re: codespaces
- :blue_book: note of intentional public AKS cluster API.
  - private cluster API adds more complexity concerns into the baseline
  - there is regulated baseline with private cluster setup. https://github.com/mspnp/aks-baseline-regulated
- :blue_book: some more docs around expectations for ACR challenge
  - maybe a hint on using `az acr import`?
- :green_book: during hack, have coaches pause at intervals and go through components that are being installed.
  - why they're being installed, etc?
  - there was still a lot of "magic" behind the scenes that made some of the challenges difficult
  - can use [upstream repo](https://github.com/mspnp/aks-secure-baseline) and [reference architecture docs](https://aka.ms/architecture/aks-baseline) for talking points
- :blue_book: add k8s extension to codespaces
  - https://marketplace.visualstudio.com/items?itemName=ms-kubernetes-tools.vscode-kubernetes-tools
- :blue_book: more bonus steps in challenges that didn't have them
  - example: add flux setup for webv as a bonus step?
- :bulb: more AKS focused challenges
- :bulb: challenges for different type of roles. app developer, cluster operator, networking team, etc
- :bulb: availability challenges. deployments, availability budgets, autoscaling, etc

**Comment by bartr** [comment]
- I think sending a link to the PnP upstream repo as a pre-read is a great idea and super easy - we should add to the hack guide
  - we are going to try a different organization technique in the APJ hack that should work better
- I like the thought of running WebV from the terminal to generate failure traffic - great idea
- Already fixed the readme and PR is merged

**Comment by bartr** [comment]
I updated asb-hack/docs/hackguide.md with the items that are ~struckout~

**Comment by bartr** [comment]
- can we break these into individual issues on the board so we can track?

@AAkindele @dsturgell @joheec @sivamu @alfredoihernandez

**Comment by kev-ms** [comment]
Added actionable items as issues on the board.
